"""Deterministic suite construction, freezing, and validation."""

from .boundaries import (
    BoundaryKind,
    SchemaBoundary,
    build_boundary_cases,
    build_boundary_scenarios,
    derive_boundaries,
    unsupported_boundary_reasons,
)
from .lint import ScenarioLintIssue, lint_scenario, lint_suite
from .mutations import (
    DEFAULT_MAX_MUTATIONS,
    DEFERRED_MUTATION_REASONS,
    MAX_MUTATIONS_PER_SUITE,
    MUTATION_CONTRACT_VERSION,
    GeneratedMutation,
    MutationKind,
    ScenarioMutation,
    build_workflow_mutations,
    inherited_hard_failure_oracles,
    mutate_scenario,
    unsupported_mutation_reasons,
)
from .realization import (
    MAX_REALIZATION_CALLS,
    REALIZATION_CREDENTIAL_ENV,
    DisabledRealizer,
    RealizationRecord,
    apply_realization,
    complete_chat,
    require_realization_consent,
)
from .selection import (
    MAX_CASES,
    SELECTION_ALGORITHM,
    CoverageModel,
    CoverageReport,
    SelectionPlan,
    select_scenarios,
    select_units,
)
from .suite import (
    DEFAULT_SUITE_FILENAME,
    FROZEN_SUITE_CONTRACT_VERSION,
    CaseLineage,
    CaseOrigin,
    FrozenCase,
    FrozenSuite,
    RejectedCase,
    build_frozen_suite,
    built_in_suite,
    configured_frozen_suite,
    default_suite_path,
    encode_frozen_suite,
    load_frozen_suite,
    resolve_suite_destination,
    write_frozen_suite,
)
from .templates import build_account_support_suite

__all__ = [
    "DEFAULT_MAX_MUTATIONS",
    "DEFAULT_SUITE_FILENAME",
    "DEFERRED_MUTATION_REASONS",
    "FROZEN_SUITE_CONTRACT_VERSION",
    "MAX_CASES",
    "MAX_MUTATIONS_PER_SUITE",
    "MAX_REALIZATION_CALLS",
    "MUTATION_CONTRACT_VERSION",
    "REALIZATION_CREDENTIAL_ENV",
    "SELECTION_ALGORITHM",
    "BoundaryKind",
    "CaseLineage",
    "CaseOrigin",
    "CoverageModel",
    "CoverageReport",
    "DisabledRealizer",
    "FrozenCase",
    "FrozenSuite",
    "GeneratedMutation",
    "MutationKind",
    "RejectedCase",
    "RealizationRecord",
    "ScenarioLintIssue",
    "ScenarioMutation",
    "SchemaBoundary",
    "SelectionPlan",
    "apply_realization",
    "build_account_support_suite",
    "build_boundary_cases",
    "build_boundary_scenarios",
    "build_frozen_suite",
    "build_workflow_mutations",
    "built_in_suite",
    "complete_chat",
    "configured_frozen_suite",
    "default_suite_path",
    "derive_boundaries",
    "encode_frozen_suite",
    "inherited_hard_failure_oracles",
    "lint_scenario",
    "lint_suite",
    "load_frozen_suite",
    "mutate_scenario",
    "require_realization_consent",
    "resolve_suite_destination",
    "select_scenarios",
    "select_units",
    "unsupported_boundary_reasons",
    "unsupported_mutation_reasons",
    "write_frozen_suite",
]
